blank_issues_enabled: true
contact_links:
  - name: Arbeitsplan Documentation
    url: https://github.com/SManuelDv/arbeitsplan/blob/master/README.md
    about: Consulte nossa documentação antes de criar uma issue
  - name: Feature Request Template
    url: https://github.com/SManuelDv/arbeitsplan/issues/new?template=feature_request.md
    about: Use este template para sugerir uma nova funcionalidade
  - name: Bug Report Template
    url: https://github.com/SManuelDv/arbeitsplan/issues/new?template=bug_report.md
    about: Use este template para reportar um bug 